language: python
sudo: false
branches:
  only:
  - master
  - yml-debug
  
python:
- 2.7
- 3.5

addons:
  apt:
    packages:
    - libfftw3-dev
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda2/bin:$PATH
- ls
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose astropy
- pip install pyfftw
# Install aotools
- git clone https://github.com/soapy/aotools.git
- cd aotools
- git checkout master
- python setup.py install
- cd ..

# Install Soapy
- git clone https://github.com/soapy/soapy.git
- cd soapy/
- git checkout master
- python setup.py install
- cd ..
script:
- nosetests --verbosity=3 test/
after_success:
- codecov
